### PR TITLE
(WIP) introducing auth callbacks

### PR DESCRIPTION
**Pull request by n0daft**

### CODE REVIEW

**Comment by IsNull** [comment]
Since these callbacks are purely informative and global in nature, we probably should use AngularJS events instead.

`$rootScope.$broadcast('loginSuccessEvent');`

`$rootScope.$on('loginSuccessEvent', function () { .... }`

**Review by IsNull — CHANGES_REQUESTED** [review]
Please refactor to Angular events.

**Comment by n0daft** [comment]
Should we use more specific event names? for example *wardenLoginSuccessEvent*. Just to make it clearer and avoid potential event name collisions.

**Comment by IsNull** [comment]
Yes I think that would be a good idea since the event namespace is _global_.

**Comment by IsNull** [comment]
Looks good so far. I would also add a logout event triggered in `Auth.logout()` after the principal has been set to null.

**Comment by IsNull** [comment]
I have added documentation how to create a new release - see the bottom of the readme file.

**Review by IsNull — APPROVED** [review]

**Pull request merged**
